# Generated by Django 4.2.1 on 2023-05-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0005_alter_video_thumbnails_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="videos",
            name="is_publish",
            field=models.BooleanField(default=False, verbose_name="Is Publish"),
        ),
    ]
