# Generated by Django 4.2.1 on 2023-06-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_alter_likes_options_alter_likes_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
